language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy redcafe/reverseproxy
  - docker tag udagram-api-feed redcafe/udagram-api-feed
  - docker tag udagram-api-user redcafe/udagram-api-user
  - docker tag udagram-frontend:local redcafe/udagram-frontend


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push redcafe/reverseproxy
  - docker push redcafe/udagram-api-feed
  - docker push redcafe/udagram-api-user
  - docker push redcafe/udagram-frontend
